apiVersion: v1
kind: Pod
metadata:
  name: my-multi-container-pod
  labels:
    purpose: demonstrate-multi-container
spec:
  volumes:
  - name: shared-volume
    emptyDir: {}

  containers:
  - name: container-one
    image: nginx
    volumeMounts:
    - name: shared-volume
      mountPath: /usr/share/nginx/html

  - name: container-two
    image: busybox
    volumeMounts:
    - name: shared-volume
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo Hello from the second container > /pod-data/index.html; sleep 30; done"]

