apiVersion: batch/v1
kind: CronJob
metadata:
  name: template-cronjob
  namespace: template
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: demo-container
            image: demo:latest
          restartPolicy: OnFailure

