apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: my-secret
  containers:
    - name: app-container
      image: nginx:latest
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume

