apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: template
  labels:
    app: demo-app
  annotations:
    annotation-key: "annotation-value"
spec:
  containers:
  - name: demo-container
    image: gcr.io/demo:latest
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "0.5"
        memory: "512Mi"
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    env:
    - name: DEMO_ENV_VAR
      value: "demo-value"
    volumeMounts:
    - name: demo-volume
      mountPath: /data
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
  volumes:
  - name: demo-volume
    emptyDir: {}
  restartPolicy: Always
  nodeSelector:
    disktype: ssd
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - demo-app
        topologyKey: "kubernetes.io/hostname"
  tolerations:
  - key: "example-key"
    operator: "Exists"
    effect: "NoSchedule"
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  imagePullSecrets:
  - name: my-registry-key

